
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haekhglsuyrfiyrkssfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZWtoZ2xzdXlyZml5cmtzc2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTQxODYsImV4cCI6MjA2MTA3MDE4Nn0.lgaCHeen3UQrCWFTK2rA_Dd1pWQFoRabVKjXmchr__U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
